### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by JingbinLiu** [madvn/DDPG#1]
Hello, thanks for your code. I've tried your code several times, It seems the code does not work now. I'm looking for an algorithm that is robust for  "pendulum-v0". Do you know any code that performs with a good convergence on this task?

**Comment by madvn** [comment]
Haha, you are right. I have still not figured out why it is not working.
Perhaps, I should've put in a note in the repo saying its not working. It
would be great if you are able to fix it. I will get back to working on
this in a couple of weeks and will hopefully be able to figure it out.
Sorry about that.

Best,
Madhvun

**Comment by madvn** [comment]
Yeah, like I say in the README
"Status: Compiles and runs but doesn't improve performance. Any help appreciated :)"

**Comment by madvn** [comment]
It works now! 😄
