### ISSUE TITLE
Test output of actor critic file error.

### ISSUE THREAD

**Issue by Jian-Yin-Shine** [madvn/DDPG#2]
tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] is not a matrix. Instead it has shape [4] [Op:MatMul]

**Comment by madvn** [comment]
[Fixed](https://github.com/madvn/DDPG/commit/c135e464d1e436b6a165fac169b1cebb9e5906b9#diff-b270f00edab73ffa4cefcbfe3aeb0040R53), thanks!
