### ISSUE TITLE
Problem about updating the actor network.

### ISSUE THREAD

**Issue by Jian-Yin-Shine** [madvn/DDPG#3]
I read your code to update the actor network,  it different from the paper.
In the paper it is : $-\frac{1}{batch\_size}\sum_{i=1}^{batch\_size}Q(s_i, a_i)$
Thank you very much for your answer.

**Comment by madvn** [comment]
Not sure what you are referring to. I have implemented the algorithm in page 5 here - https://arxiv.org/pdf/1509.02971.pdf
